### ISSUE TITLE
By training, Do you mean I can train on my own datasets?

### ISSUE THREAD

**Issue by Mr-Nobody-dey** [MNeMoNiCuZ/AuraFaceDetect#2]
Not inference, it will train as in Machine learning training?

**Comment by MNeMoNiCuZ** [comment]
It's not really training as in machine learning.
It will look at all the faces you provide it, and for each face, it will construct some numbers, describing that face in a simple way. It will then average out those numbers for the face, and then save that as a numeric representation of that face.

It can then use this as the "baseline" when it sees a new face, and compare the two, and tell you how confident it is that it is the same face in %.

So, you're not training your own model, just getting a multi-dimensional detailed vector list. Here's an example from the included sample images:

[gates.json](https://github.com/user-attachments/files/16824084/gates.json)

![image](https://github.com/user-attachments/assets/5f6f1e04-b4c4-4022-920a-b9fc794dbf8b)

Looking at the results here, you can see that when I combine both training images, I get a better certainty that it's the same character. Compared to having only 1 image as the comparison source.

The test image is a picture of him being older, so this matches better against when the training image was also older, compared to the younger image.

I hope the explanation made sense, don't hesitate to follow up with more questions.
